// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0DHIiOclpWo1nsnetVOrHvdK26YP9BSM',
    appId: '1:400305329010:web:25cca142a83422575443eb',
    messagingSenderId: '400305329010',
    projectId: 'movie-app-3f1b7',
    authDomain: 'movie-app-3f1b7.firebaseapp.com',
    storageBucket: 'movie-app-3f1b7.firebasestorage.app',
    measurementId: 'G-NB8BQFKRN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlcUXKusHSkaw7sTmgBJUmzjvZwV3K4qc',
    appId: '1:400305329010:android:41a831668806e4a95443eb',
    messagingSenderId: '400305329010',
    projectId: 'movie-app-3f1b7',
    storageBucket: 'movie-app-3f1b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9uTjpowsxHOcMMPmB9tOG3TGNkFTHWC8',
    appId: '1:400305329010:ios:fdc811ec3e58ad6d5443eb',
    messagingSenderId: '400305329010',
    projectId: 'movie-app-3f1b7',
    storageBucket: 'movie-app-3f1b7.firebasestorage.app',
    iosClientId:
        '400305329010-6mmaghdt2n4dv3ugnbq0l8o75dpgqkgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9uTjpowsxHOcMMPmB9tOG3TGNkFTHWC8',
    appId: '1:400305329010:ios:fdc811ec3e58ad6d5443eb',
    messagingSenderId: '400305329010',
    projectId: 'movie-app-3f1b7',
    storageBucket: 'movie-app-3f1b7.firebasestorage.app',
    iosClientId:
        '400305329010-6mmaghdt2n4dv3ugnbq0l8o75dpgqkgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0DHIiOclpWo1nsnetVOrHvdK26YP9BSM',
    appId: '1:400305329010:web:53450f84210fa7ed5443eb',
    messagingSenderId: '400305329010',
    projectId: 'movie-app-3f1b7',
    authDomain: 'movie-app-3f1b7.firebaseapp.com',
    storageBucket: 'movie-app-3f1b7.firebasestorage.app',
    measurementId: 'G-LMPYBG1MPD',
  );
}
